version: "3.8"
services:
  library-app:
    image: marijapost/library-app:latest  # Your pushed Docker Hub image
    container_name: library-app
    restart: always
    depends_on:
      - postgres-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/LibraryDB
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=vselena1
    ports:
      - "8080:8080"

  postgres-db:
    image: postgres:15
    container_name: library-db
    restart: always
    environment:
      POSTGRES_DB: LibraryDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: vselena1
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
