apiVersion: v1
kind: Namespace
metadata:
  name: library-namespace
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: library-db-pvc
  namespace: library-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: library-db-service
  namespace: library-namespace
spec:
  selector:
    app: library-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-db
  namespace: library-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-db
  template:
    metadata:
      labels:
        app: library-db
    spec:
      containers:
        - name: library-db
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: library-secret
                  key: SPRING_DATASOURCE_PASSWORD
            - name: POSTGRES_DB
              value: "LibraryDB"
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: library-db-pvc
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: library-config
  namespace: library-namespace
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://library-db-service.library-namespace.svc.cluster.local:5432/LibraryDB"
  SPRING_DATASOURCE_USERNAME: "postgres"
---
apiVersion: v1
kind: Secret
metadata:
  name: library-secret
  namespace: library-namespace
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: dnNlbGVuYTE=
